"""init

Revision ID: 9828991ed084
Revises: a6562fe9d103
Create Date: 2026-10-09 11:07:10.517208

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9828991ed084"
down_revision: str | None = "a6562fe9d103"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    op.execute("ALTER TYPE expensecategory ADD VALUE 'RENT'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
