"""init

Revision ID: a6562fe9d103
Revises:
Create Date: 2026-10-09 11:02:53.000427

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a6562fe9d103"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
